export type MixGame = "WARZONE" | "WARZONE_RANKED" | "BO7" | "ROCKET_LEAGUE" | "VERSUS";

/* ===========================
   TEAM NAMES (30 + 30)
   =========================== */

const WARZONE_TEAM_NAMES = [
  "Les Paras en Pantoufles",
  "La Squad du Frigo",
  "Les Snipers du Dimanche",
  "Les Balles Perdues",
  "Le Cartel des Pingouins",
  "Les Moustiques OP",
  "Les Fantômes du Gulag",
  "Les Tacticiens Égarés",
  "Les Croissants Commando",
  "La Brigade du Tilt",
  "Les Boucliers en Carton",
  "Les Ninjas du Lobby",
  "Les Pixels Vénères",
  "Les Pépites du Drop",
  "Les Grenades Poétiques",
  "La Team Pas Vu Pas Pris",
  "Les Loups du Toit",
  "Les Chasseurs de Loadout",
  "Les Snipers Mal Lunés",
  "Les Rois du Repli",
  "Les Caméléons du Smoke",
  "Les Roquettes du Placard",
  "Les Croutons Tactiques",
  "Les Saboteurs Gentils",
  "Les Dodos du Circle",
  "Les Pistaches Furtives",
  "Les Chevaliers du Ping",
  "La Patrouille du UAV",
  "Les Chèvres Galactiques",
  "Les Champs de Mines",
  "Les Alchimistes du Loot",
  "Les Pêcheurs de Plaques",
  "Les Bâtisseurs de Cover",
  "Les Monstres du Mini-Map",
  "Les VIP du Buy Station",
  "Les Architectes du Recul",
  "Les Pilotes de Drone",
  "Les Rois du Rebond",
  "Les Pros du Ping",
  "Les Discrets du Bruit",
  "Les Grincheux du Gaz",
  "Les Danseurs de Slide",
  "Les Survivants du Toit",
  "Les Poussins du Push",
  "Les Maîtres du Flanc",
  "Les Corsaires du Contrat",
  "Les Barons du Ballon",
  "Les Asticots du Smoke",
  "Les Gardiens du Loader",
  "Les Poètes du Plastron",
  "Les Glisseurs du Couloir",
  "Les Cafetiers du Combat",
  "Les Contournements Express",
  "Les Trappeurs du Tunnel",
  "Les Gourmettes du Loot",
  "Les Sorciers du Son",
  "Les Éclaireurs du Circle",
  "Les Pickups de Fortune",
  "Les Grands Stratèges",
  "Les Frères du Rebond",
  "Les Pingouins Parachutistes",
  "Les Lamas du Lobby",
  "Les Panda Paraboles",
  "Les Licornes Tactiques",
  "Les Chaussettes de Guerre",
  "Les Casques Croquants",
  "Les Briques Silencieuses",
  "Les Bananas Blindées",
  "Les Tortues Turbo",
  "Les Renards Radar",
  "Les Hiboux du Headshot",
  "Les Marmottes du Midgame",
  "Les Lynx du Loot",
  "Les Phoques en Plaques",
  "Les Hamsters Héroïques",
  "Les Koalas du Killfeed",
  "Les Chacals du Champ",
  "Les Aigles du Toit",
  "Les Corbeaux du Smoke",
  "Les Rorquals du Repli",
  "La Compagnie du Contrat",
  "La Section Bounty",
  "La Team Recon Relax",
  "Le Bureau des UAV",
  "La Firme des Flancs",
  "La Guilde du Gulag",
  "La Confrérie du Circle",
  "Le Syndicat du Slide",
  "L’Escadron du Buy",
  "La Brigade du Drop",
  "La Troupe du Timing",
  "La Clique du Cover",
  "Le Club des Plaques",
  "Les Amis du Loadout",
  "Les Artisans du Push",
  "Les Pros du Reset",
  "Les As du Self-Revive",
  "Les Virtuoses du Recoil",
  "Les Rois du Reposition",
  "Les Champions du Callout",
  "Les Vents du Flanc",
  "Les Ombres du Sud",
  "Les Éclats du Nord",
  "Les Étoiles du Toit",
  "Les Lueurs du Smoke",
  "Les Orages du Push",
  "Les Brumes du Mid",
  "Les Comètes du Drop",
  "Les Aurores du Repli",
  "Les Éclaireurs d’Argent",
  "Les Potes du Ping",
  "Les Copains du Circle",
  "Les Gardiens du Good Vibes",
  "Les Frags Sympas",
  "Les Aimants à Loot",
  "Les Calmes du Chaos",
  "Les Sages du Sprint",
  "Les Jokers du Jump",
  "Les Experts du “On y va”",
  "Les Légendes du “Je couvre”",
] as const;

const ROCKET_TEAM_NAMES = [
  "Les Boost Addicts",
  "Les Bump Diplomates",
  "Les Flips de la Chance",
  "Les Aériens du Dimanche",
  "Les Dribbleurs Timides",
  "La Brigade du Backboard",
  "Les Rotations Fantômes",
  "Les Cônes Volants",
  "Les Pivots Électriques",
  "Les Platinés Pressés",
  "Les Diamants Distraits",
  "Les Champions de Salon",
  "Les SSL du Déni",
  "Les Boosters Compulsifs",
  "Les Touches Trop Fortes",
  "Les Passes Inattendues",
  "Les Murs Magnétiques",
  "Les Rebondisseurs Pros",
  "Les Roues Souriantes",
  "Les Carrosseries Zen",
  "Les Balleux Poli(e)s",
  "Les Ailes en Plastique",
  "La Team 50/50",
  "Les Défenseurs Rêveurs",
  "Les Attaquants Patients",
  "Les Dunks Respectueux",
  "Les Double-Taps Discrets",
  "Les Kickoffs Calmes",
  "Les Freestylers Sages",
  "Les Rockets Rigolos",
] as const;

function hashToIndex(input: string, modulo: number) {
  let hash = 0;
  for (let i = 0; i < input.length; i += 1) {
    hash = (hash * 31 + input.charCodeAt(i)) >>> 0;
  }
  return modulo === 0 ? 0 : hash % modulo;
}

export function getTeamDisplayName(params: {
  game: MixGame;
  sessionId: string;
  teamNumber: number;
}) {
  const base = `${params.game}:${params.sessionId}:${params.teamNumber}`;
  if (params.game === "ROCKET_LEAGUE") {
    return ROCKET_TEAM_NAMES[hashToIndex(base, ROCKET_TEAM_NAMES.length)];
  }
  // WARZONE + WARZONE_RANKED + BO7 + VERSUS -> mêmes noms, c'est ok
  return WARZONE_TEAM_NAMES[hashToIndex(base, WARZONE_TEAM_NAMES.length)];
}
